name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Checkout Tests
        run: |
          wget https://raw.githubusercontent.com/GitCodings/Stack-BE3-Billing-Service-Starter/main/pom.xml -O pom.xml;
          wget https://raw.githubusercontent.com/GitCodings/Stack-BE3-Billing-Service-Starter/main/src/test/java/com/gitcodings/stack/billing/BillingServiceTest.java -O src/test/java/com/gitcodings/stack/billing/BillingServiceTest.java;
          wget https://raw.githubusercontent.com/GitCodings/Stack-BE3-Billing-Service-Starter/main/src/test/resources/application.yml -O src/test/resources/application.yml;
          wget https://raw.githubusercontent.com/GitCodings/Stack-BE3-Billing-Service-Starter/main/src/test/resources/billing-test-data.sql -O src/test/resources/billing-test-data.sql;
          wget https://raw.githubusercontent.com/GitCodings/Stack-BE3-Billing-Service-Starter/main/src/test/resources/empty-billing-test-data.sql -O src/test/resources/empty-billing-test-data.sql;
          wget https://raw.githubusercontent.com/GitCodings/Stack-BE3-Billing-Service-Starter/main/src/test/resources/expected-models.json -O src/test/resources/expected-models.json;
          wget https://raw.githubusercontent.com/GitCodings/Stack-BE3-Billing-Service-Starter/main/src/test/resources/idm-test-data.sql -O src/test/resources/idm-test-data.sql;
          wget https://raw.githubusercontent.com/GitCodings/Stack-BE3-Billing-Service-Starter/main/src/test/resources/users.json -O src/test/resources/users.json;
      - name: Checkout DB
        run: |
          wget https://raw.githubusercontent.com/GitCodings/Stack-Database/main/idm/idm_token_status.sql -O db/idm_token_status.sql;
          wget https://raw.githubusercontent.com/GitCodings/Stack-Database/main/idm/idm_user_status.sql -O db/idm_user_status.sql;
          wget https://raw.githubusercontent.com/GitCodings/Stack-Database/main/idm/idm_role.sql -O db/idm_role.sql;
          wget https://raw.githubusercontent.com/GitCodings/Stack-Database/main/movies/movies_genre.sql -O db/movies_genre.sql;
          wget https://raw.githubusercontent.com/GitCodings/Stack-Database/main/movies/movies_person.sql -O db/movies_person.sql;
          wget https://raw.githubusercontent.com/GitCodings/Stack-Database/main/movies/movies_movie.sql -O db/movies_movie.sql;
          wget https://raw.githubusercontent.com/GitCodings/Stack-Database/main/movies/movies_movie_genre.sql -O db/movies_movie_genre.sql;
          wget https://raw.githubusercontent.com/GitCodings/Stack-Database/main/movies/movies_movie_person.sql -O db/movies_movie_person.sql;
          wget https://raw.githubusercontent.com/GitCodings/Stack-Database/main/billing/billing_movie_price.sql -O db/billing_movie_price.sql;
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install MySQL
        run: brew install mysql;
      - name: Get Stripe API Key
        run: |
          sed -i '' 's|${STRIPE_API_KEY}|"'$STRIPE_API_KEY'"|' src/test/resources/application.yml;
        env:
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      - name: Setup DB
        run: |
          mysql.server start;
          mysql -uroot < db/schema.sql;
          mysql -uroot < db/idm_token_status.sql;
          mysql -uroot < db/idm_user_status.sql;
          mysql -uroot < db/idm_role.sql;
          mysql -uroot < db/movies_genre.sql;
          mysql -uroot < db/movies_person.sql;
          mysql -uroot < db/movies_movie.sql;
          mysql -uroot < db/movies_movie_genre.sql;
          mysql -uroot < db/movies_movie_person.sql;
          mysql -uroot < db/billing_movie_price.sql;
      - name: Autograder
        uses: education/autograding@v1
      - name: Delete Stripe API Key
        run: |
          rm -P src/test/resources/application.yml;